// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkyOvDXmpR9bFMo32Dh-x2WBjP2QpWFOY',
    appId: '1:902352527562:android:20b4c5a25c4d7163b8d433',
    messagingSenderId: '902352527562',
    projectId: 'quizzapp-10b75',
    storageBucket: 'quizzapp-10b75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdTkV1JL8T4cT3iHvm-tHMCUQpQqsAyQM',
    appId: '1:902352527562:ios:74ebac616bebe2bdb8d433',
    messagingSenderId: '902352527562',
    projectId: 'quizzapp-10b75',
    storageBucket: 'quizzapp-10b75.appspot.com',
    androidClientId: '902352527562-ee2u9mp3412hfrddm3jvpecp8j076vk7.apps.googleusercontent.com',
    iosClientId: '902352527562-nq2p60j9qg0t1s333nes2b4kd5taukm0.apps.googleusercontent.com',
    iosBundleId: 'com.pkmisha.quizzapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdTkV1JL8T4cT3iHvm-tHMCUQpQqsAyQM',
    appId: '1:902352527562:ios:74ebac616bebe2bdb8d433',
    messagingSenderId: '902352527562',
    projectId: 'quizzapp-10b75',
    storageBucket: 'quizzapp-10b75.appspot.com',
    androidClientId: '902352527562-ee2u9mp3412hfrddm3jvpecp8j076vk7.apps.googleusercontent.com',
    iosClientId: '902352527562-nq2p60j9qg0t1s333nes2b4kd5taukm0.apps.googleusercontent.com',
    iosBundleId: 'com.pkmisha.quizzapp',
  );
}
